#ifndef ANIMATIONS_H_
#define ANIMATIONS_H_

#include "Config.h"

#ifdef USE_ANIMATION_1

#define VALUES_IN_RANGE_FROM_MINUS_1_TO_PLUS_1 3
#define MAX_VALUES_IN_RANGE_USED_BY_ANIMATION VALUES_IN_RANGE_FROM_MINUS_1_TO_PLUS_1

#define COUNT_OF_LEDS_IN_ANIMATION 1
#define COUNT_OF_FUNCTIONS_IN_ANIMATION 3

#endif

#ifdef USE_ANIMATION_2
// FIXME doesn't fit in the FLASH.

#define VALUES_IN_RANGE_FROM_MINUS_50_TO_PLUS_50 101
#define MAX_VALUES_IN_RANGE_USED_BY_ANIMATION VALUES_IN_RANGE_FROM_MINUS_50_TO_PLUS_50

#define COUNT_OF_LEDS_IN_ANIMATION 240
#define COUNT_OF_FUNCTIONS_IN_ANIMATION 1

#endif

extern const unsigned char animationData[];
uint32_t getAnimationSizeInBytes(void);

#endif /* ANIMATIONS_H_ */
